name: Get Food Rescue Hero Data

on:
  workflow_dispatch:

jobs:
  get-rescues-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        run: uv python install --project data
      
      - name: Activate venv & Install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install -r data/pyproject.toml
      
      - name: Run Python script to get data
        env:
          FOOD_RESCUE_HERO_USERNAME: ${{ secrets.FOOD_RESCUE_HERO_USERNAME }}
          FOOD_RESCUE_HERO_PASSWORD: ${{ secrets.FOOD_RESCUE_HERO_PASSWORD }}
        run: uv run python data/src/food_rescue_hero.py --dest-file-path /tmp/csv/rescues.csv
      
      - name: Confirm CSV exists
        run: |
          echo 'Listing files in /tmp/csv dir'
          ls /tmp/csv
    
    - id: 'checkout'
      uses: 'actions/checkout@v4'
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCT_JSON }}'
    
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: '/tmp/csv/rescues.csv'
        destination: havens-harvest-data
